% With TICV
mavol( ...
	'assr_label','TNAD-x-228989-x-228989-x-601-x-Multi_Atlas_v2', ...
	'seg_niigz','../INPUTS2/orig_target_seg.nii.gz', ...
	'ticv_niigz','../INPUTS2/orig_target_ticv.nii.gz', ...
	'vol_txt','../INPUTS2/target_processed_label_volumes.txt', ...
	'out_dir','../OUTPUTS2' ...
	);

% Without
mavol( ...
	'assr_label','VISIONS_2017-x-3082-x-3082-x-003-x-Multi_Atlas', ...
	'seg_niigz','../INPUTS1/orig_target_seg.nii.gz', ...
	'vol_txt','../INPUTS1/target_processed_label_volumes.txt', ...
	'out_dir','../OUTPUTS1' ...
	);
