mavol( ...
	'assr_label','TESTPROJ-x-TESTSUBJ-x-TESTSESS-x-TESTSCAN-x-MultiAtlas', ...
	'seg_niigz','../INPUTS/orig_target_seg.nii.gz', ...
	'vol_txt','../INPUTS/target_processed_label_volumes.txt', ...
	'out_dir','../OUTPUTS' ...
	);
